apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: hughexp
    provider: https://github.com
    providerKind: github
    repositories:
    - name: jx-aspnet-app7
    - name: jx-aspnet-app8
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
